workers:
    docker_compose: ~
    sass:
        cmd: ['symfony', 'console', 'sass:build', '--watch']
    tailwind:
        cmd: ['symfony', 'console', 'tailwind:build', '--watch']

http:
    use_gzip: true
