name: Release on NPM

on:
  push:
    tags:
        - 'v2.*.*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
            with:
              ref: 2.x

          - name: Configure Git
            run: |
              git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git config --global user.name "github-actions[bot]"

          - name: Extract version from tag
            run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

          - run: npm i -g corepack && corepack enable
          - uses: actions/setup-node@v4
            with:
              cache: 'yarn'
              cache-dependency-path: |
                yarn.lock
                package.json
                src/**/package.json
          - run: yarn --immutable

          - name: Update version of JS packages
            run: yarn workspaces foreach -pA exec "npm version ${{ env.VERSION }} --no-git-tag-version --no-workspaces-update"

          - name: Commit changes
            run: |
              git add .
              git commit -m "Update versions to ${{ env.VERSION }}"

          - name: Replace local "workspace:*" occurrences
            run: |
              yarn workspaces foreach -pA exec "sed -i 's/\"workspace:\*\"/\"${{ env.VERSION }}\"/g' package.json"

          - name: Publish on NPM
            env:
              NPM_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
            run: yarn workspaces foreach -A --no-private npm publish --access public --tolerate-republish

          - name: Push changes
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: git push origin 2.x
