name: Toolkit Kits Code Quality

on:
    push:
        paths:
            - 'src/Toolkit/kits/**'
    pull_request:
        paths:
            - 'src/Toolkit/kits/**'

jobs:
    kits-cs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                php-version: 8.3

            - name: Install composer packages
              uses: ramsey/composer-install@v3
              with:
                working-directory: src/Toolkit

            - name: Check kits code style
              run: php vendor/bin/twig-cs-fixer check kits
              working-directory: src/Toolkit
